<?xml version="1.0" encoding="utf-8"?>

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:export="export" version="1.0">  
  <xsl:output method="xml" encoding="UTF-8" indent="yes"/>  
  <export:data>
    <uiConfig> 
      <applicationInfo name="CorelDRAW" framework="CorelDRAW" version="14" userConfiguration="true" localizedLang="CS"/>  
      <commandBars> 
        <commandBarData guid="53175317-5317-5317-5317-100000000001" type="toolbar" nonLocalizableName="tisn201600401" userCaption="Tisn工具" userCreated="true"> 
          <container floatWidth="32767" imageSize="small"> 
            <item guidRef="53175317-5317-5317-5317-900000000001"/>  
            <item guidRef="53175317-5317-5317-5317-900000000002"/>  
            <item guidRef="53175317-5317-5317-5317-900000000003"/>  
            <item guidRef="53175317-5317-5317-5317-900000000004"/> 
          </container> 
        </commandBarData> 
      </commandBars>  
      <items> 
        <whatsNew sinceVersion="off"/>  
        <itemData guid="53175317-5317-5317-5317-900000000001" dynamicCommand="cdrplugin1_导出图片" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" icon="guid://53175317-5317-5317-5317-110000000001"> 
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAAAQAI
AAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBwcHBwcHAAAAAAAAAAAAAAAAAAAAAAAH
BwcHBwcHBwcHBwcHBwAABwcHBwcHBwcHBwcHBwcAAAcHBwcHBwcHBwcAAAAAAAAHBwcHAAAA7wcH
AAcHBwAAAAAAAAcHBwAAAAcHBwcAAAcABwcHBwcH7QAHBwcHAAAHBwcHBwcHBwcHBwcHBwAABwcH
BwcHBwcHAAAHBwcAAAcHBwcHBwcHBwAABwcHAAAHBwcHBwcHBwcHBwcHBwAABwcHBwcHBwcHBwcH
BwcAAAcHBwcHBwcHBwcHBwcHAAAAAAAAAAAAAAAAAAAAAAAHBwcHBwcHBwcHBwcHBwcH8PDwAKCg
oADw8PAAAAAAAA==</userSmallBitmap>  
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAAAQAI
AAAAAABAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAcHBwcHBwcHBwcHBwcHBwcHBwcHAAAAAAcHBwcHBwcHBwcHBwcHBwcH
BwcHAAAAAAcHBwcHBwcHBwcHBwcHBwcHBwcHAAAAAAcHBwcHBwcHBwcHBwcHBwcHBwcHAAAAAAcH
BwcHBwcHBwcHBwcHB0MAAAAAAAAAAAcHBwcHB+8AAAAHBwcHFAAAB20AAAAAAAcHBwcHAAAAAAAA
BwcHAAAHBwcHAAAAAAAH7wAAAAcHBwcAAOwAAAcHBwcHAAAAAAAAAAATBwcHBwcHAAAA6gcHBwcH
AAAAAAcHBwcHBwcHBwcHBwf3BwcHBwcHAAAAAAcHBwcHBwcHBwcHBwcHBwcHBwcHAAAAAAcHBwcH
BwcHBwcHBwcADwcHBwcHAAAAAAcHBwcHBwcHBwcHB+oAABAHBwcHAAAAAAcHBwcHBwcHBwcHB+wA
ABIHBwcHAAAAAAcHBwcHBwcHBwcHBwfrkgcHBwcHAAAAAAcHBwcHBwcHBwcHBwcHBwcHBwcHAAAA
AAcHBwcHBwcHBwcHBwcHBwcHBwcHAAAAAAcHBwcHBwcHBwcHBwcHBwcHBwcHAAAAAAcHBwcHBwcH
BwcHBwcHBwcHBwcHAAAAAAcHBwcHBwcHBwcHBwcHBwcHBwcHAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwfw8PAAoKCgAPDw8AAAAAAA</userLargeBitmap> 
        </itemData>  
        <itemData guid="53175317-5317-5317-5317-900000000002" dynamicCommand="cdrplugin1_转换" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" icon="guid://53175317-5317-5317-5317-110000000002"> 
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAAAQAI
AAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBwcHBwcHBwcHBwcHAAAAAAcHBwcHBwcH
BwcHBwAHBwAHBwcHBwcHBwcHEAAABwcAABAHBwcHBwcHEAAHBwAABwcAEAcHBwcHBwAHBwcHBwcH
BwAHBwcHAAAABwcHBwcHBwcAAAAHBwAHBwAHBwcHBwcABwcABwcABwcABwcHBwcHAAcHAAcHAAAA
BwcHBwcHBwcAAAAHBwcHAAcHBwcHBwcHAAcHBwcHBxAABwcAAAcHABAHBwcHBwcHEAAABwcAABAH
BwcHBwcHBwcHAAcHAAcHBwcHBwcHBwcHBwAAAAAHBwcHBwcHBwcHBwcHBwcHBwcHBwcH8PDwAKCg
oADw8PAAAAAAAA==</userSmallBitmap>  
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAAAQAI
AAAAAABAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcH
AAAAAAcHBwcHBwcHBwcHBwcHBwcHBwcAAAcHAAAHBwcHBwcHBwcHBwcHBwcHBwcABwcHBwAHBwcH
BwcHBwcHBwcHBwcHBwAABwcHBwAABwcHBwcHBwcHBwcHBwcAAOoAAAcHAADqAAAHBwcHBwcHBwcH
BwAABwcHAAAAAAcHBwAABwcHBwcHBwcHBwAHBwcHBwcHBwcHBwcABwcHBwcHBwcHAOoHBwcHBwcH
BwcHBwfqAAcHBwcHBwAAAAAHBwcHBwcHBwcHBwcAAAAABwcHAAAHBwAABwcHBwcHBwcHBwAABwcA
AAcHAAcHBwcABwcHBwcHBwcHBwAHBwcHAAcHAAcHBwcABwcHBwcHBwcHBwAHBwcHAAcHAAAHBwAA
BwcHBwcHBwcHBwAABwcAAAcHBwAAAAAHBwcHBwcHBwcHBwcAAAAABwcHBwcHAOoHBwcHBwcHBwcH
BwfqAAcHBwcHBwcHBwAHBwcHBwcHBwcHBwcABwcHBwcHBwcHBwAABwcHAAAAAAcHBwAABwcHBwcH
BwcHBwcAAOoAAAcHAADqAAAHBwcHBwcHBwcHBwcHBwAABwcHBwAABwcHBwcHBwcHBwcHBwcHBwcA
BwcHBwAHBwcHBwcHBwcHBwcHBwcHBwcAAAcHAAAHBwcHBwcHBwcHBwcHBwcHBwcHAAAAAAcHBwcH
BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwfw8PAAoKCgAPDw8AAAAAAA</userLargeBitmap> 
        </itemData>  
        <itemData guid="53175317-5317-5317-5317-900000000003" dynamicCommand="cdrplugin1_裁切标记" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" icon="guid://53175317-5317-5317-5317-110000000003"> 
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAA AQAIAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAZGRkAMzMzADMz MwBMTEwAZmZmAGZmZgB/f38AmZmZAJmZmQCysrIA8PDwAMzMzADMzMwA5eXlAP///wAAADMA AABmAAAAmQAzAGYAMzNmAAAAzAAzAJkAAAD/AGYAmQAzM5kAAAD/ADMAzABmAMwAMwD/ADMz zABmM5kAMwD/AGYA/wAzM/8AZmaZAGYzzABmAP8AmQDMAGYz/wCZAP8AmTPMAGZmzACZAP8A zAD/AJlmzACZM/8AzAD/AMwz/wCZmcwAADNmAAAzmQAAM8wAAGaZADNmmQAAM/8AADP/AABm zAAAZv8AAJnMADNmzAAAZv8AM5nMAACZ/wAAzP8AZpnMAAAzAAAAZgAAADMzAABmMwAAmQAA AGZmAACZMwAzZjMAAMwAADNmZgAA/wAAAJlmAAD/AAAzmTMAAMwzADOZZgAAzGYAM8wzAAD/ MwAA/zMAAJmZADP/MwAzmZkAAMyZAGaZZgAA/2YAM8xmAAD/ZgAAzMwAAP+ZAGaZmQAzzJkA ZsxmAAD/mQAz/2YAM/+ZADPMzABmzJkAAP/MAAD/zABm/2YAM//MAGb/mQBmzMwAAP//AJnM mQCZzMwAmf+ZAGb/zACZ/8wAzP/MADMzAAAzZgAAM5kAAGZmAABmmQAAM8wAAGZmMwAz/wAA ZpkzAJmZAABmzAAAM/8AAGbMMwCZzAAAZv8AAGb/AACZmTMAzMwAAJn/AACZ/wAAmZlmAGb/ MwCZzDMAmf8zAMz/AACZzGYAzP8AAMzMMwCZ/2YAzP8zAMzMZgD//wAA//8AAP//MwDM/2YA zMyZAMz/mQD//2YA//+ZAP//zABmAAAAOSAgADkmJgBmMwAAmQAAAJkzAADMAAAAZjMzAP8A AAD/AAAAzDMAAJlmAACZMzMAaVNTAG9YWAB1XV0AzDMzAP8zAADMZgAA/zMAAJlmMwCZZmYA zGYzAP8zMwD/ZgAAzJkAAP9mAACOc3IAkHVzAP9mMwDMZmYA/5kAAMyZMwD/mQAAnn9/AP/M AAD/ZmYA/8wAAMyZZgD/mTMA/5lmAP/MMwDMmZkA/5mZAP/MZgD/zJkA/8zMADMAMwA5JSgA OSYoADomKAA5JikAOiYpADonKQA7KCoAZgAzAEArLgBNOTsAZgBmAJkAMwBfTU8AzAAzAJkA ZgBmM2YAalZXAGtXWQD/ADMAmQCZAMwAZgCZM2YAel9hAP8AZgDMM2YAmTOZAMwAmQDMM5kA zDOZAJlmmQD/AJkAzADMAP8zZgCff4AAp4aIAP8AzADMZpkAzDPMALORkwDMZswA/2aZAP8z zAD/AP8A/wD/AMyZzAD/ZswA/zP/AP+ZzAAODg4ODg4ODw8ODg4ODg4ODg4ODg4ODhEPDg4O Dg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg7GtAXcDg4ODg4ODg4ODvayv7kEAAALDg4ODg4O Dg+rv8O5BQUEAA4ODg4ODg7Av8PDudME0wDcDg4ODw8OtLm5uasF09MEBQ8PDw8PDyIfHx8b PmFhYVsODw8ODg4wJCsrH2FxcXFpDg4ODg4ODxsrKx9hcXFhDw4ODg4ODg4NGyQfYXFhDQ4O Dg4ODg4ODg8wIltwDg4ODg4ODg4ODg4ODg8ODg4ODg4ODg4ODg4ODg4PDw4ODg4ODg4ODg4O Dg4ODw8ODg4ODg4O8PDwAKCgoADw8PAAAAAAAA==</userSmallBitmap>  
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAA AQAIAAAAAABAAgAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAZGRkAMzMzADMz MwBMTEwAZmZmAGZmZgB/f38AmZmZAJmZmQCysrIA8PDwAMzMzADMzMwA5eXlAP///wAAADMA AABmADMAZgAAAJkAAADMADMAmQAzM2YAAAD/AGYAmQAzM5kAAAD/ADMAzAAzAP8AZgDMADMz zAAzAP8AZjOZAGZmmQBmAP8AmQDMAGYA/wBmM8wAmTPMAJkA/wBmZswAmQD/AJlmzADMAP8A zAD/AJmZzAAAM2YAADOZAABmmQAAM8wAADP/AABmzAAzZpkAAGb/AACZzAAzZswAAJn/ADOZ zAAAzP8AZpnMAAAzAAAAMzMAAGYAAABmMwAAmQAAAGZmAACZMwAzZjMAAMwAADNmZgAAzDMA M5kzAACZZgAA/wAAAP8AADPMMwAAzGYAAP8zAACZmQAzmWYAAP8zAGaZZgAA/2YAAMyZADP/ MwAzzGYAM5mZAAD/ZgBmmZkAAP+ZADPMmQBmzGYAAP+ZAADMzAAz/2YAAP/MAGbMmQAz/5kA M8zMAAD/zABm/2YAmcyZAGb/mQAz/8wAAP//AGbMzABm/8wAmf+ZAJnMzACZ/8wAzP/MADMz AAAzZgAAZmYAADOZAAAzzAAAZpkAAGZmMwBmzAAAZpkzADP/AACZmQAAM/8AAGbMMwBm/wAA mZkzAGb/AACZzAAAmf8AAJmZZgCZ/wAAmcwzAMzMAABm/zMAzP8AAMzMMwCZzGYAzP8AAJn/ MwD//wAAzP8zAMzMZgD//wAAmf9mAP//MwDMzJkAzP9mAP//ZgDM/5kA//+ZAP//zABmAAAA OSAgADkmJgCZAAAAZjMAAMwAAACZMwAAZjMzAP8AAACZMzMAzDMAAP8AAACZZgAAzDMzAJlm MwD/MwAA/zMAAMxmAACJbm0AzJkAAP9mAAD/ZgAAmWZmAP8zMwDMZjMAjnNyAJB1cwCXenkA mHx6AP+ZAAD/mQAAzJkzAMxmZgD/ZjMAnn9/AP/MAAD/zAAAzJlmAP9mZgD/mTMA/8wzAP+Z ZgDMmZkA/8xmAP+ZmQD/zJkA/8zMADMAMwA5JSgAOSYoADomKAA5JikAOScpADomKQA6JygA OicpADsoKgBmADMASDM1AEw4OQCZADMAZgBmAFhFRwBdRkkAXklKAF9NTwBjTE8AzAAzAGYz ZgCZAGYAYk9RAGpWVwBrV1kAcllaAHJcXQDMAGYAmTNmAJkAmQD/ADMAzDNmAP8AZgDMAJkA mTOZAItubwD/M2YAzADMAP8AmQCZZpkAzDOZAMwzmQCnhogAzDPMAP8AzADMZpkAs5GTAP8z zADMZswA/2aZAP8A/wDMmcwA/2bMAP+ZzAAODg4ODg4ODg4ODgAADg4ODg4ODg4ODg4ODg4O Dg4ODg4ODgAADg4ODg4ODg4ODg4ODg4ODg4ODg4ODgAADg4ODg4ODg4ODg4ODg4ODg4ODg4O DgAADg4ODg4ODg4ODg4ODg4ODg4ODg4RDQAADREODg4ODg4ODg4ODg4ODg4OEQqmqwAEAAQI Dg4ODg4ODg4ODg4ODg4ReKu9va0FBQQABBEODg4ODg4ODg4ODhF4rb29va0FBQUFAM0ODg4O Dg4ODg4ODgurvb29va0FBQUFBQAKDg4ODg4ODg4OEaa9vb29va0FBQUFBQQEEQ4ODg4ODg4O D6u9vb29va3NBM3Nzc4ADg4ODg4AAAAACqatra2traYEypycnM0AAAAAAAAAAAAAChggICAg IBtRYGBgYGBgAAAAAAAODg4ODxgqKioqKiBga2tra2tgDg4ODg4ODg4OmSMlKioqKhtga2tr a2tRyA4ODg4ODg4ODgsYKioqKhtga2tra2BbDg4ODg4ODg4ODg7eICoqKhtga2tra0jIDg4O Dg4ODg4ODg6Z3hgqKiBga2tgSMgODg4ODg4ODg4ODg4ODgsjGxtRYFkLyA4ODg4ODg4ODg4O Dg4ODg6ZDgoKDsgODg4ODg4ODg4ODg4ODg4ODg4ODgAADg4ODg4ODg4ODg4ODg4ODg4ODg4O DgAADg4ODg4ODg4ODg4ODg4ODg4ODg4ODgAADg4ODg4ODg4ODg4ODg4ODg4ODg4ODgAADg4O Dg4ODg4ODg7w8PAAoKCgAPDw8AAAAAAA</userLargeBitmap> 
        </itemData>  
        <itemData guid="53175317-5317-5317-5317-900000000004" dynamicCommand="cdrplugin1_全部" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" icon="guid://53175317-5317-5317-5317-110000000004"> 
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAA AQAIAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAZGRkAMzMzADMz MwBMTEwAZmZmAGZmZgB/f38AmZmZAJmZmQCysrIA8PDwAMzMzADMzMwA5eXlAP///wAAADMA AABmAAAAmQAzAGYAMzNmAAAAzAAzAJkAAAD/AGYAmQAzM5kAAAD/ADMAzABmAMwAMwD/ADMz zABmM5kAMwD/AGYA/wAzM/8AZmaZAGYzzABmAP8AmQDMAGYz/wCZAP8AmTPMAGZmzACZAP8A zAD/AJlmzACZM/8AzAD/AMwz/wCZmcwAADNmAAAzmQAAM8wAAGaZADNmmQAAM/8AADP/AABm zAAAZv8AAJnMADNmzAAAZv8AM5nMAACZ/wAAzP8AZpnMAAAzAAAAZgAAADMzAABmMwAAmQAA AGZmAACZMwAzZjMAAMwAADNmZgAA/wAAAJlmAAD/AAAzmTMAAMwzADOZZgAAzGYAM8wzAAD/ MwAA/zMAAJmZADP/MwAzmZkAAMyZAGaZZgAA/2YAM8xmAAD/ZgAAzMwAAP+ZAGaZmQAzzJkA ZsxmAAD/mQAz/2YAM/+ZADPMzABmzJkAAP/MAAD/zABm/2YAM//MAGb/mQBmzMwAAP//AJnM mQCZzMwAmf+ZAGb/zACZ/8wAzP/MADMzAAAzZgAAM5kAAGZmAABmmQAAM8wAAGZmMwAz/wAA ZpkzAJmZAABmzAAAM/8AAGbMMwCZzAAAZv8AAGb/AACZmTMAzMwAAJn/AACZ/wAAmZlmAGb/ MwCZzDMAmf8zAMz/AACZzGYAzP8AAMzMMwCZ/2YAzP8zAMzMZgD//wAA//8AAP//MwDM/2YA zMyZAMz/mQD//2YA//+ZAP//zABmAAAAOSAgADkmJgBmMwAAmQAAAJkzAADMAAAAZjMzAP8A AAD/AAAAzDMAAJlmAACZMzMAaVNTAG9YWAB1XV0AzDMzAP8zAADMZgAA/zMAAJlmMwCZZmYA zGYzAP8zMwD/ZgAAzJkAAP9mAACOc3IAkHVzAP9mMwDMZmYA/5kAAMyZMwD/mQAAnn9/AP/M AAD/ZmYA/8wAAMyZZgD/mTMA/5lmAP/MMwDMmZkA/5mZAP/MZgD/zJkA/8zMADMAMwA5JSgA OSYoADomKAA5JikAOiYpADonKQA7KCoAZgAzAEArLgBNOTsAZgBmAJkAMwBfTU8AzAAzAJkA ZgBmM2YAalZXAGtXWQD/ADMAmQCZAMwAZgCZM2YAel9hAP8AZgDMM2YAmTOZAMwAmQDMM5kA zDOZAJlmmQD/AJkAzADMAP8zZgCff4AAp4aIAP8AzADMZpkAzDPMALORkwDMZswA/2aZAP8z zAD/AP8A/wD/AMyZzAD/ZswA/zP/AP+ZzAAODg4ODjQlGhoqNA8ODg4ODg4ODi0aGi00DzQ0 Dw8RDg4ODg8aGg8ODg4ODg4REQ4ODg4tGiUODg4ODg4ODg4ODg4OLRoqDg4ODg4ODg4ODg4O DjQaGg4ODg4ODg4ODg4ODg4OGholDg4ODg4ODg4ODg4ODi0aGjQODg4ODg4ODg4ODg4OGhoa EQ4ODg4ODg4ODg4ODg8aGiUODg4ODg4ODg4ODg4OLRoaKg4ODg4ODg4ODg4ODg4lGho0Dg4O Dg4ODg4ODg4OERoaGhEODg4ODhE0NBEODg4RGholDg4ODg4OESolGiUlKhoaGjQODg4ODg4O ETQlGhoaGiURDg4O8PDwAKCgoADw8PAAAAAAAA==</userSmallBitmap>  
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAA AQAIAAAAAABAAgAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAZGRkAMzMzADMz MwBMTEwAZmZmAGZmZgB/f38AmZmZAJmZmQCysrIA8PDwAMzMzADMzMwA5eXlAP///wAAADMA AABmADMAZgAAAJkAAADMADMAmQAzM2YAAAD/AGYAmQAzM5kAAAD/ADMAzAAzAP8AZgDMADMz zAAzAP8AZjOZAGZmmQBmAP8AmQDMAGYA/wBmM8wAmTPMAJkA/wBmZswAmQD/AJlmzADMAP8A zAD/AJmZzAAAM2YAADOZAABmmQAAM8wAADP/AABmzAAzZpkAAGb/AACZzAAzZswAAJn/ADOZ zAAAzP8AZpnMAAAzAAAAMzMAAGYAAABmMwAAmQAAAGZmAACZMwAzZjMAAMwAADNmZgAAzDMA M5kzAACZZgAA/wAAAP8AADPMMwAAzGYAAP8zAACZmQAzmWYAAP8zAGaZZgAA/2YAAMyZADP/ MwAzzGYAM5mZAAD/ZgBmmZkAAP+ZADPMmQBmzGYAAP+ZAADMzAAz/2YAAP/MAGbMmQAz/5kA M8zMAAD/zABm/2YAmcyZAGb/mQAz/8wAAP//AGbMzABm/8wAmf+ZAJnMzACZ/8wAzP/MADMz AAAzZgAAZmYAADOZAAAzzAAAZpkAAGZmMwBmzAAAZpkzADP/AACZmQAAM/8AAGbMMwBm/wAA mZkzAGb/AACZzAAAmf8AAJmZZgCZ/wAAmcwzAMzMAABm/zMAzP8AAMzMMwCZzGYAzP8AAJn/ MwD//wAAzP8zAMzMZgD//wAAmf9mAP//MwDMzJkAzP9mAP//ZgDM/5kA//+ZAP//zABmAAAA OSAgADkmJgCZAAAAZjMAAMwAAACZMwAAZjMzAP8AAACZMzMAzDMAAP8AAACZZgAAzDMzAJlm MwD/MwAA/zMAAMxmAACJbm0AzJkAAP9mAAD/ZgAAmWZmAP8zMwDMZjMAjnNyAJB1cwCXenkA mHx6AP+ZAAD/mQAAzJkzAMxmZgD/ZjMAnn9/AP/MAAD/zAAAzJlmAP9mZgD/mTMA/8wzAP+Z ZgDMmZkA/8xmAP+ZmQD/zJkA/8zMADMAMwA5JSgAOSYoADomKAA5JikAOScpADomKQA6JygA OicpADsoKgBmADMASDM1AEw4OQCZADMAZgBmAFhFRwBdRkkAXklKAF9NTwBjTE8AzAAzAGYz ZgCZAGYAYk9RAGpWVwBrV1kAcllaAHJcXQDMAGYAmTNmAJkAmQD/ADMAzDNmAP8AZgDMAJkA mTOZAItubwD/M2YAzADMAP8AmQCZZpkAzDOZAMwzmQCnhogAzDPMAP8AzADMZpkAs5GTAP8z zADMZswA/2aZAP8A/wDMmcwA/2bMAP+ZzAAODg4ODg4ODg8rGhoaGiEwEQ4ODg4ODg4ODg4O Dg4OKxoaGh8hKyEhKzAwEQ4ODg4ODg4ODg4rGhohMA8RDg4ODg8wMDAPDg4ODg4ODg8aGhow EREOEREODg4ODg8wEQ4ODg4ODisaGhoRDg4ODg4ODg4ODg4ODg4ODg4ODh8aGisODg4ODg4O Dg4ODg4ODg4ODg4ODh8aGjAODg4ODg4ODg4ODg4ODg4ODg4ODiEaGiEODg4ODg4ODg4ODg4O Dg4ODg4ODjAaGhoRDg4ODg4ODg4ODg4ODg4ODg4ODhEaGhofDg4ODg4ODg4ODg4ODg4ODg4O Dg4hGhoaIQ4ODg4ODg4ODg4ODg4ODg4ODg4RGhoaGjAODg4ODg4ODg4ODg4ODg4ODg4OKxoa GhoRDg4ODg4ODg4ODg4ODg4ODg4ODhoaGhohDg4ODg4ODg4ODg4ODg4ODg4ODg8aGhoaKw4O Dg4ODg4ODg4ODg4ODg4ODg4rGhoaGg8ODg4ODg4ODg4ODg4ODg4ODg4OHxoaGhoRDg4ODg4O Dg4ODg4ODg4ODg4OERoaGhohDg4ODg4ODg4ODg4ODg4ODg4ODg8aGhoaKw4ODg4ODg4ODhEP Dg4ODg4ODg4wGhoaGg8ODg4ODg4ODhEhITARDg4ODg4OMBoaGhoODg4ODg4ODg4OKxoaHysr MDAwKxoaGhorDg4ODg4ODg4ODg4wGhoaGhoaGhoaGhorDg4ODg4ODg4ODg4ODhEwKyEfGhoa HysRDg4ODg7w8PAAoKCgAPDw8AAAAAAA</userLargeBitmap> 
        </itemData> 
      </items> 
    </uiConfig> 
  </export:data>  
  <xsl:template match="node()[count(*)='0']|@*"> 
    <xsl:copy-of select="."/> 
  </xsl:template>  
  <xsl:template match="node()"> 
    <xsl:copy> 
      <xsl:apply-templates select="node()|@*"/> 
    </xsl:copy> 
  </xsl:template>  
  <xsl:template match="uiConfig"> 
    <xsl:copy> 
      <xsl:apply-templates select="node()|@*"/>  
      <xsl:if test="not(./items)"> 
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/> 
      </xsl:if>  
      <xsl:if test="not(./items)"> 
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/> 
      </xsl:if>  
      <xsl:if test="not(./items)"> 
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/> 
      </xsl:if>  
      <xsl:if test="not(./items)"> 
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/> 
      </xsl:if>  
      <xsl:if test="not(./items)"> 
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/> 
      </xsl:if>  
      <xsl:if test="not(./commandBars)"> 
        <xsl:copy-of select="document('')/*/export:data/uiConfig/commandBars"/> 
      </xsl:if> 
    </xsl:copy> 
  </xsl:template>  
  <xsl:template match="uiConfig/items"> 
    <xsl:copy> 
      <xsl:apply-templates select="node()|@*"/>  
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000001'])"> 
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000001']"/> 
      </xsl:if> 
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000002'])"> 
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000002']"/> 
      </xsl:if> 
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000003'])"> 
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000003']"/> 
      </xsl:if> 
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000004'])"> 
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000004']"/> 
      </xsl:if> 
    </xsl:copy> 
  </xsl:template>  
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000001']"> 
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000001']"/> 
  </xsl:template>  
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000002']"> 
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000002']"/> 
  </xsl:template>  
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000003']"> 
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000003']"/> 
  </xsl:template>  
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000004']"> 
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000004']"/> 
  </xsl:template>  
  <xsl:template match="uiConfig/commandBars"> 
    <xsl:copy> 
      <xsl:apply-templates select="node()|@*"/>  
      <xsl:if test="not(./commandBarData[@guid='53175317-5317-5317-5317-100000000001'])"> 
        <xsl:copy-of select="document('')/*/export:data/uiConfig/commandBars/commandBarData[@guid='53175317-5317-5317-5317-100000000001']"/> 
      </xsl:if> 
    </xsl:copy> 
  </xsl:template>  
  <xsl:template match="uiConfig/commandBars/commandBarData[@guid='53175317-5317-5317-5317-100000000001']"> 
    <xsl:copy-of select="document('')/*/export:data/uiConfig/commandBars/commandBarData[@guid='53175317-5317-5317-5317-100000000001']"/> 
  </xsl:template> 
</xsl:stylesheet>