<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:export="export" version="1.0">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<export:data>
		<uiConfig>
			<applicationInfo name="CorelDRAW" framework="CorelDRAW" version="14" userConfiguration="true" localizedLang="CS"/>
			<commandBars>
        <commandBarData guid="53175317-5317-5317-5317-100000000001" type="toolbar" nonLocalizableName="tisn201600401" userCaption="Tisn工具" userCreated="true">
          <container>
            <item guidRef="53175317-5317-5317-5317-900000000001"/>
            <item guidRef="53175317-5317-5317-5317-900000000002"/>
            <item guidRef="53175317-5317-5317-5317-900000000003"/>
            <item guidRef="53175317-5317-5317-5317-900000000004"/>
            <item guidRef="53175317-5317-5317-5317-900000000007"/>
            <item guidRef="53175317-5317-5317-5317-900000000008"/>
            <item guidRef="53175317-5317-5317-5317-900000000009"/>
            <item guidRef="266435b4-6e53-460f-9fa7-f45be187d400"/>
            <item guidRef="53175317-5317-5317-5317-900000000098"/>
            <item guidRef="53175317-5317-5317-5317-900000000099"/>
          </container>
        </commandBarData>
      </commandBars>
			<items>
				<whatsNew sinceVersion="off"/>  <itemData guid="53175317-5317-5317-5317-900000000001" dynamicCommand="cdrplugin1_导出图片" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" userCaption="导出图片" userToopTip="导出图片">
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAAAQAI
AAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBwcHBwcHAAAAAAAAAAAAAAAAAAAAAAAH
BwcHBwcHBwcHBwcH7wAABwcHBwcHBwcHBwcHB+8AAAcHBwcHBwcHBwdtAADrAAAHBwfvAAAABwfr
AAfvDgAAbe9DAOwHbQD3AAcHB+8AABAAEwcHBwf3ABUHBwfvAAAHBwcHBwcHBwcHBwcH7wAABwcH
BwcHBwfsAO8HB+8AAAcHBwcHBwcHQwDrBwfvAAAHBwcHBwcHBwfvBwcH7wAABwcHBwcHBwcHBwcH
B+8AAAcHBwcHBwcHBwcHBwfvAADv7+/v7+/v7+/v7+/vkgAAAAAAAAAAAAAAAAAAAAAA8PDwAKCg
oADw8PAAAAAAAA==</userSmallBitmap>
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAAAQAI
AAAAAABAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAku/v7+/v7+/v7+/v7+/v7+/v7+/vAAAA7wcHBwcHBwcHBwcHBwcHBwcH
BwcHAAAA7wcHBwcHBwcHBwcHBwcHBwcHBwcHAAAA7wcHBwcHBwcHBwcHBwcHBwfv+JIHAAAA7wcH
BwcHBwcHBwcHBwcHB20AAAAQAAAA7wcHBwcHB+9tEvcHBwcHEwAAEQ4AAAAA9wcHBwfsAABDFQAA
BwfvAG0HBwcHAAAADm337EMAD+wHB20AQ/cSEAcHBwcHAAAAAAAAAAAABwcHBwfsAAAA7AcHBwcH
AAAA7wfvBwcHBwcHBwcHB++SBwcHBwcHAAAA7wcHBwcHBwcHBwcHBwcHBwcHBwcHAAAA7wcHBwcH
BwcHBwcHBwfvBwcHBwcHAAAA7wcHBwcHBwcHBwcHBxEAAG0HBwcHAAAA7wcHBwcHBwcHBwcHB0MA
AOsHBwcHAAAA7wcHBwcHBwcHBwcHB5IOQwcHBwcHAAAA7wcHBwcHBwcHBwcHBwcHBwcHBwcHAAAA
7wcHBwcHBwcHBwcHBwcHBwcHBwcHAAAA7wcHBwcHBwcHBwcHBwcHBwcHBwcHAAAA7wcHBwcHBwcH
BwcHBwcHBwcHBwcHAAAAku/v7+/v7+/v7+/v7+/v7+/v7+/vAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwfw8PAAoKCgAPDw8AAAAAAA</userLargeBitmap>
        </itemData>
        <itemData guid="53175317-5317-5317-5317-900000000002" dynamicCommand="cdrplugin1_转换" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" userCaption="转换" userToopTip="转换">
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAAAQAI
AAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBwcHBwcHBwcHBwcHDg4A9wcHBwcHBwcH
BwcH70MHBwAHBwcHBwcHBwcHEgAOB+8AAAcHBwcHBwcHERQHFQAABwcABwcHBwcHkg8HBwcHBwcH
BwAHBwcHEQASBwcHBwcHBwcAAPcHEm0HEe0HBwcHBwcA7wcABxAHB/htBwcHBwcHAAcHDgfvABMA
BwcHBwcHBxUOQw4HBwcV7AcHBwcHBwcHAO8HBwcHBwAHBwdt7QcHFBIHBwcHBwfvAOwA+BESDxEH
BwcHBwcHBwcVEwcHAJIHBwcHBwcHBwcHBwAHbREHBwcHBwcHBwcHBwfvEBIHBwcHBwcH8PDwAKCg
oADw8PAAAAAAAA==</userSmallBitmap>
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAAAQAI
AAAAAABAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcH
EhAQ7wcHBwcHBwcHBwcHBwcHBwcHBwcRbQcHABEHBwcHBwcHBwcHBwcHBwcHB+8ABwcHQwDvBwcH
BwcHBwcHBwcHBwcHkhUABwcHEwAVBwcHBwcHBwcHBwcHB+8RD+wSEfj4ABLsABHvBwcHBwcHBwcH
BxEABwcHAAAAFQcHFAARBwcHBwcHBwcHEgAUBwcH7W1tBwcHBxQABwcHBwcHBwfvAOwHBwcHBwcH
BwcHBwfsFe8HBwcH9xEAABIHBwcHBwcHBwcHBwcSAAARBwcHDgBDDgAVBwcHBwcHBwcHBxUAE0MA
7wcHDgcHB/gABwcHBwcHBwcHbQD4BwcHEAcHDgcHB/gABwcHBwcHBwcHbQD4BwcHEAcHAG0H7xEA
BwcHBwcHBwcH7QARBwdtEgcH9xEAABIHBwcHBwcHBwcHBwcSAAARBwcHBwfvAOwHBwcHBwcHBwcH
BwfsFe8HBwcHBwcHAA8HBwcHBwcHBwcHBwcPkgcHBwcHBwcHBxEABwcHAAAAFQcHFAARBwcHBwcH
BwcHB+8RD+wSEfj4ABLsABHvBwcHBwcHBwcHBwcHAAAA7wcHDgAAEgcHBwcHBwcHBwcHBwcHB+8A
BwcHQwDvBwcHBwcHBwcHBwcHBwcHBwcRbQcHABEHBwcHBwcHBwcHBwcHBwcHBwf3AA4ODvcHBwcH
BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwfw8PAAoKCgAPDw8AAAAAAA</userLargeBitmap>
        </itemData>
        <itemData guid="53175317-5317-5317-5317-900000000003" dynamicCommand="cdrplugin1_一键PS" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" userCaption="一键PS" userToopTip="一键PS">
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAAAQAI
AAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAAAAAAAAAAAAAAAAAAAAAADwcHBwcHBwcHBwcHBwcHAA8H
bQcHBwcHBwdtBwcHBwAPBwAHBwcHBwcHAA8HBwcADwcABwcHBwcHB/cA6gcHAA/vAAcHBwcHBwcH
EwD3BwAP7wCSbQcHBwcHB5IAbQcAD+8A7AD3BwcHBwcAQwcHAA/vAAcVAAcHBwcADgcHBwAP7wAH
BxAABwcAAAcHBwcAD+8AB+wAEAeSAOsHBwcHAA/vABEA+AcHB+sA7wcHBwAP7wAABwcHBwcHFAAH
BwcAD+8RBwcHBwcHBwcPBwcHAA8HBwcHBwcHBwcHBwcHBwAADw8PDw8PDw8PDw8PDw8A8PDwAKCg
oADw8PAAAAAAAA==</userSmallBitmap>
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAAAQAI
AAAAAABAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw8PDw8PDw8P
Dw8PDw8PDw8PDw8PAAAABwcHBwcHBwcHBwcHBwcHBwcHBwcHDwAABwcSkgcHBwcHBwcHBwcH+AcH
BwcHDwAABwcA6wcHBwcHBwcHBwf4DpIHBwcHDwAABwcAbQcHBwcHBwcHBwcHAAAVBwcHDwAABwcA
bQcHBwcHBwcHBwcHDgAABwcHDwAAB+8AbQcHBwcHBwcHBwcH+AAA7AcHDwAAB+8AbfcSBwcHBwcH
BwcHBwcQABAHDwAAB+8AbZIABwcHBwcHBwcHB5IOAG0HDwAAB+8A6u0A7AcHBwcHBwcH7w4AEwcH
DwAAB+8A6gcTAA/vBwcHBwcHAAAQBwcHDwAAB+8A6gcHAABDBwcHBwfqAA73BwcHDwAAB+8AEgcH
EQAABwcHB/gAAO0HBwcHDwAAB+8AEgcH70MADu8HDgAABwcHBwcHDwAAB+8AEwcHDgAAkgcHDgAA
BwcHBwcHDwAAB+8AEwfqAAATBwcH7AAA7QcHBwcHDwAAB+8AAAAA9wcHBwcHBwfqABAHBwcHDwAA
B+8AAAASBwcHBwcHBwcHAAAUBwcHDwAAB+8ADuwHBwcHBwcHBwcHEQAABwcHDwAAB+/qBwcHBwcH
BwcHBwcHB/fvBwcHDwAABwcHBwcHBwcHBwcHBwcHBwcHBwcHDwAABwcHBwcHBwcHBwcHBwcHBwcH
BwcHDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw8PAAoKCgAPDw8AAAAAAA</userLargeBitmap>
        </itemData>
        <itemData guid="53175317-5317-5317-5317-900000000004" dynamicCommand="cdrplugin1_裁切标记" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" userCaption="裁切标记" userToopTip="裁切标记">
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAAAQAI
AAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHDgcHBwcHBwcHBwcHBwcHBw4HBwcHBwcHBwcH
BwcHBwcOBwcHBwcHBwcHBwcHBwdtABWSBwcHBwcHBwcHB/iy0wBDQw8HBwcHBwcHB/fT09MAQ0ND
DwcHBwcHBweK09PTAENDQ0OSBwcHBwcH09PT0wBDQ0NDFAcHBw4ODgAAAAAADg4ODgAODg4HBwcY
GBgYAPv7+/ttBwcHBwcHRBgYGAD7+/v7BwcHBwcHBwdiGBgA+/v77AcHBwcHBwcHB0QYAPsw9wcH
BwcHBwcHBwcHBw4HBwcHBwcHBwcHBwcHBwcOBwcHBwcHBwcHBwcHBwcHDgcHBwcHBwcH8PDwAKCg
oADw8PAAAAAAAA==</userSmallBitmap>
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAAAQAI
AAAAAABAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBw4OBwcHBwcHBwcHBwcHBwcHBwcHBwcH
Bw4OBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw4OBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw4OBwcHBwcH
BwcHBwcHBwcHBwcHBwcHBw4OBwcHBwcHBwcHBwcHBwcHBwcH92yK0wAAQw8VBwcHBwcHBwcHBwcH
BwcHirLT0wAAQ0ND+AcHBwcHBwcHBwcHBwf409PT0wAAQ0NDD/gHBwcHBwcHBwcHB2yy09PT0wAA
Q0NDQ0MVBwcHBwcHBwcH94rT09PT0wAAQ0NDQ0MPBwcHBwcHBwcHbbLT09PT0wAAQ0NDQ0NDBwcH
BwcODg4OAAAAAAAAAAAAAAAAAAAADg4ODg4ODg4OAAAAAAAAAAAADg4ODg4ODg4ODg4HBwcHRBgY
GBgYGAAO+/v7+/v7BwcHBwcHBwcH92IYGBgYGAAO+/v7+/swBwcHBwcHBwcHB0QYGBgYGAAO+/v7
+/tKBwcHBwcHBwcHB/c/GBgYGAAO+/v7+zD3BwcHBwcHBwcHBwcHPxgYGAAO+/v77AcHBwcHBwcH
BwcHBwcH90RiGAAOODBKBwcHBwcHBwcHBwcHBwcHBwf3ZwAAbfcHBwcHBwcHBwcHBwcHBwcHBwcH
Bw4OBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw4OBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw4OBwcHBwcH
BwcHBwcHBwcHBwcHBwcHBw4OBwcHBwcHBwcHBwfw8PAAoKCgAPDw8AAAAAAA</userLargeBitmap>
        </itemData>
        <itemData guid="53175317-5317-5317-5317-900000000007" dynamicCommand="cdrplugin1_二维码" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" userCaption="二维码" userToopTip="二维码">
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAAAQAI
AAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAAAAAAAAAHAAcAAAcHAAcAAAcHBwcABwAOBwAHBwcABwAH
AA4HAAcABwcHAAAAAAcABwAABwAHAA4HDgcABwAAAAcHBwcOBwcHB+8OBwAABwAODg4ODgcHDg4H
BwcABwAHAAcHB+8OBwfvDgcAAA4HDgAHDg4OAA4HDg4H7wAHBwcABw4H7w7vDu8ADg4HAAAHBwcH
Bw7vDgAOB+8OBwAHDg4ODg4OB+8O7w4AAAAAAAAHBwfvDgcHAA4OBwcHBwAABw4OBw4HBw7vDgcA
DgcAAAcADgcADgfvAA4HAAAHAAAHBwcHDgcHDgcOBwcHBwAAAAAAAA4HBwcHAAAAAAAA8PDwAKCg
oADw8PAAAAAAAA==</userSmallBitmap>
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAAAQAI
AAAAAABAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAAAAAAAAAAAAAHAAAHAAAABwcHAAAHAAAAAAAAAAAAAA4H
Dg4HDgAABwcHAAAHAAAABwcHBwcHDg4HDgAABwcOBwcHBwcABwcABwcAAA4HAAAHAAAHBwcHDgAA
AAAABwcABwcAAA4HDg4HDg7vBwcHDgAAAAAABwcABwcOAA4HDg4HDg4OBwcOBwcOBwcAAAAABwcH
BwcHAA4HBwcHBwcHDg4HDgAABwcABwcHBwcHDg4HBwcHBwcHDg4HAAAOBwcAAAAAAA4ADg7vBwcO
Dg7vBwcHAAAHAAAHAAAHBwcHB+8OBwcHB+8OBwcOAAAOBwcHAAAHBwcHB+8O7wcHB+8OBwcOAAAO
BwcAAAAHAAAODg4ADg7vDg4A7wcHDg4HBwcHAAAHAA7vB+8O7+8O7+8ODg4O7wcODgAHDg4HDg4H
B+8O7+8O7+8ODg4ABwcADgAHBwcHBwcHDg4HDg4ADg7vB+8ABwcABwcAAA4AAA4AAA4HB+8O7+8O
DgAODgAADgAAAA4AAA4AAA4HBwcO7+8ODgAODgAOAAAABwcHBwcHAA4HBwcODgAABwcHBwcHAAAA
BwcOAA4HDg4HBwcO7+8OBwcODg4HAAAABwcAAAAHAADvBwcO7+8ABwcAAAAHAAAABwcAAA4HAAAA
BwcHDgAABwcOAAAHAAAABwcHBwcHDg4HBwcOBwcOBwcHBwcHAAAABwcHBwcHAAAHBwcOBwcABwcH
BwcHAAAAAAAAAAAAAAAHBwcHBwcAAAAAAAAAAADw8PAAoKCgAPDw8AAAAAAA</userLargeBitmap>
        </itemData>
        <itemData guid="53175317-5317-5317-5317-900000000008" dynamicCommand="cdrplugin1_同类选择" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" userCaption="同类选择" userToopTip="同类选择">
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAAAQAI
AAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBwcHBwcHBwft7e3t7e3t7e3tBwcHB/j4
Dg4ODg4ODg4ODu8HBwcA/////////////w7vBwcHAP///xf1//////8O7wcHBwD///T5+b3/////
Du8HBwcA///5+fn54////w7vBwcHAP8W+flH+flH//8O7wcHBwD/+fn5/0f5+fn/Du8HBwcAveP5
4///R/n5+Q/vBwcHAP////////9H+fn5bwcHBwD//////////0f5+flHBwcA////////////R/n5
+fkHAA4ODg4ODg4ODg4g+flHBwcHBwcHBwcHBwcHB0eTBwcHBwcHBwcHBwcHBwcHBwcH8PDwAKCg
oADw8PAAAAAAAA==</userSmallBitmap>
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAAAQAI
AAAAAABAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcH
BwcHBwcHBwcHBwcHBwcHBwcHDw8PDw8PDw8PDw8PDw8PBwcHBwfv+Pj4Dg4ODg4ODg4ODg4ODg4P
BwcHBwfsDg4ODg4ODg4ODg4ODg4OAA4PBwcHBwfs////////////////////Dg4PBwcHBwfs////
////4/X/////////Dg4PBwcHBwfs//////+U+Ufz////////Dg4PBwcHBwfs/////+P5+fn5lP//
////Dg4PBwcHBwfs////vfn5+fn5+eP/////Dg4PBwcHBwfs////R/n5+fn5+fkX////Dg4PBwcH
Bwfs//+9+fn5FvVH+fn5+b3/Dg4PBwcHBwfs//8X+fn5vf/1+fn5+fkWDg4PBwcHBwfs/5T5+fn5
////R/n5+fn5Dg4PBwcHBwfs///////z//////VH+fn5+fkeBwcHBwfs///////////////1+fn5
+fn5BwcHBwfs////////////////R/n5+fn5FwcHBwfs//////////////////VH+fn5+flHBwfs
///////////////////1+fn5+fn5kwfs////////////////////IPn5+fn5Rwfv7Ozs7Ozs7Ozs
7Ozs7Ozs7BxH+flvBwcHBwcHBwcHBwcHBwcHBwcHBwcHR5MHBwcHBwcHBwcHBwcHBwcHBwcHBwcH
BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwfw8PAAoKCgAPDw8AAAAAAA</userLargeBitmap>
        </itemData>
        <itemData guid="53175317-5317-5317-5317-900000000009" dynamicCommand="cdrplugin1_字体识别" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" userCaption="字体识别" userToopTip="字体识别">
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAAAQAI
AAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBwcHBwcHBwcHBwcHB5MHBwcHBwcHBwcH
BwcH+fn5bxcXBwcHBwcHBwcHR/lvkwcHBweT7wcHBwcHB/n5BwcHBwcHBwcHBwcHBwf5+QcHBwcH
BwcHBwcHBwcH+fnvBwcHBwcHBwcHBwcHB5P5+QcHBwcHBwcHBwcHBwcH+fn5BwcHBwcHBwcHBwcH
Bwf5+W8HBwcHBwcHBwcHBwcHb/n5BwcHBwcHBwcHBwcHBwf5+fkHBwcHBwcHB+8HBwcHB/n5RwcH
BwcHBwcHb/kXb29v+fnvBwcHBwcHBwcHk0f5+fn5BwcHBwcHBwcHBwcHBwcHBwcHBwcH8PDwAKCg
oADw8PAAAAAAAA==</userSmallBitmap>
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAAAQAI
AAAAAABAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcH
BwcHBwcHBwcHBwcHBwcHBwcHBwcHB5MX+fn5R2+TBwcHBwcHBwcHBwcHBwcHb/n5+flHbxdHbwcH
BwcHBwcHBwcHBwcH+fn5k5OTBwcHk29vBwcHBwcHBwcHBweT+flHBwcHBwcHBwcHBwcHBwcHBwcH
BwcX+fmTBwcHBwcHBwcHBwcHBwcHBwcHBwcX+fnvBwcHBwcHBwcHBwcHBwcHBwcHBwdv+flvBwcH
BwcHBwcHBwcHBwcHBwcHBwfv+fn5BwcHBwcHBwcHBwcHBwcHBwcHBwcH+fn5BwcHBwcHBwcHBwcH
BwcHBwcHBwcHR/n5+ZMHBwcHBwcHBwcHBwcHBwcHBwcHk/n5+fkHBwcHBwcHBwcHBwcHBwcHBwcH
Bxf5+fkXBwcHBwcHBwcHBwcHBwcHBwcHBweT+fn5kwcHBwcHBwcHBwcHBwcHBwcHBwcH+fn5RwcH
BwcHBwcHBwcHBwcHBwcHBwcHR/n5+RcHBwcHBwcHBwcHBwcHBwcHBwcHB5P5+fn5BwcHBwcHBwcH
BwcHkwcHBwcHBwdv+fn5BwcHBwcHBwcHBwcHF0dvBwcHBwcH+fn5bwcHBwcHBwcHBwcHBwcHR/n5
+fn5+fn5+ZMHBwcHBwcHBwcHBwcHB5NvR/n5+fn5RwcHBwcHBwcHBwcHBwcHBwcHBweTk5OTBwcH
BwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwfw8PAAoKCgAPDw8AAAAAAA</userLargeBitmap>
        </itemData>
        <itemData guidRef="266435b4-6e53-460f-9fa7-f45be187d400"/>
        <itemData guid="53175317-5317-5317-5317-900000000098" dynamicCommand="cdrplugin1_超级撤销" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" userCaption="超级撤销" userToopTip="如果执行了大批量操作，请使用这个">
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAAAQAI
AAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHB0dHR0dHbwcHBwcHBwcHB0f5+fn5+fn5RwcHBwcH
Bwdv+fn5+fn5+fn5BwcHBwcHB5OTk5OTR/n5+fkHBwcHBwcHBwcHBweT+fn5BwcHBwcHBwcHBwcH
B0f5+RcHBwcHBwcHBwcHBwfv+fn5BwcHBwcHBwcHBwcH7/n5+QcHBwcHB0cHBwcHBxf5+UcHBwcH
b/n5BwcHBwf5+fnvBweT+fn5+QcH7xf5+fn5Bwf5+fn5+fn5+fn5+fn5BwdH+fn5+fn5+fn5+fn5
BwcHBwf5+fn5+fn5+RfvBwcHBwcHB5P5+fkHBwcHBwcHBwcHBwcHBxf5BwcHBwcHBwcH8PDwAKCg
oADw8PAAAAAAAA==</userSmallBitmap>
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAAAQAI
AAAAAABAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHk0dHR0dHR0cXkwcHBwcHBwcHBwcHBwcH+fn5
+fn5+fn5+UdvBwcHBwcHBwcHBwcH+fn5+fn5+fn5+fn5+W8HBwcHBwcHBwcH+fn5+fn5+fn5+fn5
+flvBwcHBwcHBwcHR/n5+fn5+fn5+fn5+fn5BwcHBwcHBwcHBwcHBwcHBwcHb/n5+fn5bwcHBwcH
BwcHBwcHBwcHBwcHB5P5+fn5+QcHBwcHBwcHBwcHBwcHBwcHBweT+fn5+W8HBwcHBwcHBwcHBwcH
BwcHBwcH+fn5+UcHBwcHBwcHBwcHBwcHBwcHBwcH+fn5+fkHBwcHBwcHBwcHBwcHBwcHBwcH+fn5
+fkHBwcHBwcHBwcHBwcHBwcHBwcH+fn5+UcHBwcHBwcHBweTBwcHBwcHBwcH+fn5+UcHBwcHBwcH
k0f5BwcHBwcHBweT+fn5+W8HBwcHB2/5+fn5BwcHBwcHk0f5+fn5FwcHBwcHR/n5+fn5BwcHB++T
+fn5+fn5kwcHB+8X+fn5+fn5+fn5+fn5+fn5+fn5BweT+fn5+fn5+fn5+fn5+fn5+fn5+RcHBweT
+fn5+fn5+fn5+fn5+fn5+fn5bwcHBwcHb/n5+fn5+fn5+fn5+fn5+fkXBwcHBwcHBwcHR/n5+fn5
BwcHBwcHBwcHBwcHBwcHBwcHB5NH+fn5BwcHBwcHBwcHBwcHBwcHBwcHBwcH+fn5BwcHBwcHBwcH
BwcHBwcHBwcHBwcHBweTBwcHBwcHBwcHBwcHBwfw8PAAoKCgAPDw8AAAAAAA</userLargeBitmap>
        </itemData>
        <itemData guid="53175317-5317-5317-5317-900000000099" dynamicCommand="cdrplugin1_超级重做" dynamicCategory="ab489730-8791-45d2-a825-b78bbe0d6a5d" userCaption="超级重做" userToopTip="如果执行了大批量操作，请使用这个">
          <userSmallBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAAAAAQAAKAAAABAAAAAQAAAAAQAI
AAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHk0f5+fn5bwcHBwcHBweT+fn5+fn5+fkHBwcHBwdv
+fn5+fn5+fn5BwcHBwfv+fn5+W+Tk5OTBwcHBwcH+fn5RwcHBwcHBwcHBwcHB/n5+QcHBwcHBwcH
BwcHBwf5+fkHBwcHBwcHBwcHBwcH+fn5BwcHBwcHBwcHBwcHB/n5+QcHBwcHB28HBwcHBwf5+fn5
BwcHBwf5+e8HBwcH7/n5+flvk5OT+fn5RwcHBwdv+fn5+fn5+fn5+fn5FwcHB5P5+fn5+fn5+fn5
+fmTBwcHB5NHR0dH+fn5+W8HBwcHBwcHBwcHB/n5RwcHBwcHBwcHBwcHBwf5BwcHBwcH8PDwAKCg
oADw8PAAAAAAAA==</userSmallBitmap>
          <userLargeBitmap xmlns:dt="urn:schemas-microsoft-com:datatypes" dt:dt="bin.base64">//8BABAAV0NtblVJX1VJSXRlbUJtcAAAAAAAAAAAKAAAAAAEAABAAgAAKAAAABgAAAAYAAAAAQAI
AAAAAABAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICAAADAwMAA
wNzAAPDKpgAzAAAAAAAzADMAMwAzMwAAFhYWABwcHAAiIiIAKSkpAFVVVQBNTU0AQkJCADk5OQCA
fP8AUFD/AJMA1gD/7MwAxtbvANbn5wCQqa0AAP8zAAAAZgAAAJkAAADMAAAzAAAAMzMAADNmAAAz
mQAAM8wAADP/AABmAAAAZjMAAGZmAABmmQAAZswAAGb/AACZAAAAmTMAAJlmAACZmQAAmcwAAJn/
AADMAAAAzDMAAMxmAADMmQAAzMwAAMz/AAD/ZgAA/5kAAP/MADP/AAD/ADMAMwBmADMAmQAzAMwA
MwD/AP8zAAAzMzMAMzNmADMzmQAzM8wAMzP/ADNmAAAzZjMAM2ZmADNmmQAzZswAM2b/ADOZAAAz
mTMAM5lmADOZmQAzmcwAM5n/ADPMAAAzzDMAM8xmADPMmQAzzMwAM8z/ADP/MwAz/2YAM/+ZADP/
zAAz//8AZgAAAGYAMwBmAGYAZgCZAGYAzABmAP8AZjMAAGYzMwBmM2YAZjOZAGYzzABmM/8AZmYA
AGZmMwBmZmYAZmaZAGZmzABmmQAAZpkzAGaZZgBmmZkAZpnMAGaZ/wBmzAAAZswzAGbMmQBmzMwA
Zsz/AGb/AABm/zMAZv+ZAGb/zADMAP8A/wDMAJmZAACZM5kAmQCZAJkAzACZAAAAmTMzAJkAZgCZ
M8wAmQD/AJlmAACZZjMAmTNmAJlmmQCZZswAmTP/AJmZMwCZmWYAmZmZAJmZzACZmf8AmcwAAJnM
MwBmzGYAmcyZAJnMzACZzP8Amf8AAJn/MwCZzGYAmf+ZAJn/zACZ//8AzAAAAJkAMwDMAGYAzACZ
AMwAzACZMwAAzDMzAMwzZgDMM5kAzDPMAMwz/wDMZgAAzGYzAJlmZgDMZpkAzGbMAJlm/wDMmQAA
zJkzAMyZZgDMmZkAzJnMAMyZ/wDMzAAAzMwzAMzMZgDMzJkAzMzMAMzM/wDM/wAAzP8zAJn/ZgDM
/5kAzP/MAMz//wDMADMA/wBmAP8AmQDMMwAA/zMzAP8zZgD/M5kA/zPMAP8z/wD/ZgAA/2YzAMxm
ZgD/ZpkA/2bMAMxm/wD/mQAA/5kzAP+ZZgD/mZkA/5nMAP+Z/wD/zAAA/8wzAP/MZgD/zJkA/8zM
AP/M/wD//zMAzP9mAP//mQD//8wAZmb/AGb/ZgBm//8A/2ZmAP9m/wD//2YAIQClAF9fXwB3d3cA
hoaGAJaWlgDLy8sAsrKyANfX1wDd3d0A4+PjAOrq6gDx8fEA+Pj4APD7/wCkoKAAgICAAAAA/wAA
/wAAAP//AP8AAAD/AP8A//8AAP///wAHBwcHBwcHF0dH+fn5+flHBwcHBwcHBwcHBwcHB2/5+fn5
+fn5+fn5kwcHBwcHBwcHBwdv+fn5+fn5+fn5+fn5RwcHBwcHBwcHB2/5+fn5+fn5+fn5+fn5bwcH
BwcHBwcHb/n5+fn5+fn5+fn5+fn5BwcHBwcHBwcH+fn5+fn5BwcHBwcHBwcHBwcHBwcHBwcH+fn5
+UfvBwcHBwcHBwcHBwcHBwcHBwdv+fn5+ZMHBwcHBwcHBwcHBwcHBwcHBwdH+fn5kwcHBwcHBwcH
BwcHBwcHBwcHBwf5+fn57wcHBwcHBwcHBwcHBwcHBwcHBwf5+fn5BwcHBwcHBwcHBwcHBwcHBwcH
BwdH+fn5kwcHBwcHBwcHBwcHBwcHBwcHBwcX+fn5RwcHBwcHBwcHR28HBwcHBwcHBwdv+fn5+ZMH
BwcHBwcH+flHBwcHBwcHBwcH+fn5+fn5BwcHBwcH+fn5+flvBwcHBwcH+fn5+fn5R2+Tk5OT+fn5
+fn5kwcHBwcHb/n5+fn5+fn5+fn5+fn5+fn5+UeTBwcHBwdv+fn5+fn5+fn5+fn5+fn5+fn5+W8H
BwcH+fn5+fn5+fn5+fn5+fn5+fn5R5MHBwcHB2/5+fn5+fn5+fn5+fn5+flHBwcHBwcHBwcHBwcH
BwcH+fn5+fn5BwcHBwcHBwcHBwcHBwcHBwcH+fn5+UeTBwcHBwcHBwcHBwcHBwcHBwcH+fn5kwcH
BwcHBwcHBwcHBwcHBwcHBwcHF+8HBwcHBwcHBwfw8PAAoKCgAPDw8AAAAAAA</userLargeBitmap>
        </itemData>
      </items>
		</uiConfig>
	</export:data>  <xsl:template match="node()[count(*)='0']|@*">
    <xsl:copy-of select="."/>
  </xsl:template>
  <xsl:template match="node()">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
    </xsl:copy>
  </xsl:template>
  <xsl:template match="uiConfig">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
      <xsl:if test="not(./items)">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/>
      </xsl:if>
      <xsl:if test="not(./items)">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/>
      </xsl:if>
      <xsl:if test="not(./items)">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/>
      </xsl:if>
      <xsl:if test="not(./items)">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/>
      </xsl:if>
      <xsl:if test="not(./items)">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/>
      </xsl:if>
      <xsl:if test="not(./items)">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/>
      </xsl:if>
      <xsl:if test="not(./items)">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/>
      </xsl:if>
      <xsl:if test="not(./items)">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/>
      </xsl:if>
      <xsl:if test="not(./items)">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/>
      </xsl:if>
      <xsl:if test="not(./items)">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items"/>
      </xsl:if>
      <xsl:if test="not(./commandBars)">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/commandBars"/>
      </xsl:if>
    </xsl:copy>
  </xsl:template>
  <xsl:template match="uiConfig/items">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000001'])">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000001']"/>
      </xsl:if>
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000002'])">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000002']"/>
      </xsl:if>
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000003'])">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000003']"/>
      </xsl:if>
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000004'])">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000004']"/>
      </xsl:if>
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000007'])">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000007']"/>
      </xsl:if>
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000008'])">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000008']"/>
      </xsl:if>
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000009'])">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000009']"/>
      </xsl:if>
      <xsl:if test="not(./itemData[@guid='266435b4-6e53-460f-9fa7-f45be187d400'])">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='266435b4-6e53-460f-9fa7-f45be187d400']"/>
      </xsl:if>
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000098'])">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000098']"/>
      </xsl:if>
      <xsl:if test="not(./itemData[@guid='53175317-5317-5317-5317-900000000099'])">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000099']"/>
      </xsl:if>
    </xsl:copy>
  </xsl:template>
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000001']">
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000001']"/>
  </xsl:template>
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000002']">
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000002']"/>
  </xsl:template>
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000003']">
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000003']"/>
  </xsl:template>
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000004']">
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000004']"/>
  </xsl:template>
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000007']">
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000007']"/>
  </xsl:template>
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000008']">
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000008']"/>
  </xsl:template>
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000009']">
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000009']"/>
  </xsl:template>
  <xsl:template match="uiConfig/items/itemData[@guid='266435b4-6e53-460f-9fa7-f45be187d400']">
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='266435b4-6e53-460f-9fa7-f45be187d400']"/>
  </xsl:template>
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000098']">
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000098']"/>
  </xsl:template>
  <xsl:template match="uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000099']">
    <xsl:copy-of select="document('')/*/export:data/uiConfig/items/itemData[@guid='53175317-5317-5317-5317-900000000099']"/>
  </xsl:template>
  <xsl:template match="uiConfig/commandBars">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*"/>
      <xsl:if test="not(./commandBarData[@guid='53175317-5317-5317-5317-100000000001'])">
        <xsl:copy-of select="document('')/*/export:data/uiConfig/commandBars/commandBarData[@guid='53175317-5317-5317-5317-100000000001']"/>
      </xsl:if>
    </xsl:copy>
  </xsl:template>
  <xsl:template match="uiConfig/commandBars/commandBarData[@guid='53175317-5317-5317-5317-100000000001']">
    <xsl:copy-of select="document('')/*/export:data/uiConfig/commandBars/commandBarData[@guid='53175317-5317-5317-5317-100000000001']"/>
  </xsl:template>
</xsl:stylesheet>
